### ISSUE TITLE
Please add dump in twig files

### ISSUE THREAD

**Issue by PhilETaylor** [akovalyov/DebugStatementsFixers#6]
Please consider adding removal of dump in twig templates in Symfony apps - thats what brought me your repo today anyway :) 

```

{% dump(some.var) %}
or
{% some.var|dump %}

```

**Comment by akovalyov** [comment]
@PhilETaylor thanks for the proposal. Unfortunately, that's not doable in the scope of this tiny plugin as Twig is not PHP and is not processable by PHP-CS-Fixer, which is the tool this plugin was made for.
P.S. It seems that I should adjust notifications settings in GitHub. Apologies for delayed answer.
